### ISSUE TITLE
seek design help

### ISSUE THREAD

**Issue by johanndiedrick** [jdiedrick/whitefragility#19]
multicultural designers:
- [x] johann
- [x] francis
- [x] fei
- [x] alex tatusian
- [x] stacey
- [x] julie
- [x] brian
- [x] zach

**Comment by outer-space** [comment]
could ask Stacey & Julie too when we're in Philly

**Comment by johanndiedrick** [comment]
alex:
riso
newspaper
endless editions: http://www.endlesseditions.com/proposals/
