### ISSUE TITLE
reading progress indicator

### ISSUE THREAD

**Issue by frnsys** [jdiedrick/whitefragility#40]
as you're clicking through, the left-side shows progress via subheader being highlighted or arrow pointing to it or whatever

**Comment by johanndiedrick** [comment]
we did this with underlining. check it out and lmk if that works! if so feel free to close: http://w-f.is

**Comment by johanndiedrick** [comment]
@frnsys

**Comment by johanndiedrick** [comment]
@frnsys closing for now feel free to reopen!
