### ISSUE TITLE
add author's name to main page

### ISSUE THREAD

**Issue by outer-space** [jdiedrick/whitefragility#62]
<img width="1270" alt="screen shot 2016-11-16 at 11 21 53" src="https://cloud.githubusercontent.com/assets/2447862/20355247/b22841c0-abee-11e6-9bc4-5016216f36a5.png">

**Comment by outer-space** [comment]
<img width="1266" alt="screenshot 2016-11-16 11 38 29" src="https://cloud.githubusercontent.com/assets/2447862/20355835/c1334744-abf0-11e6-9ef4-0eca5ad5b135.png">

**Comment by johanndiedrick** [comment]
closed with 6cbfb46c6b4ceee4b7339aa045b6c5623ece7c17
